AllCops:
  NewCops: enable
  SuggestExtensions: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Max: 1024

Metrics/MethodLength:
  Max: 1024

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
